name = "create-perfect-world"
author = "ilGuappo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1af12390e3f512e93adf8371c499ecf54386052b5d8d1beca928289027e84897"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
