name = "create-perfect-world"
author = "ilGuappo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8213cdcb002342969820a5d15b96513f78092677de40eb0cdf14816a699c4e89"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
