name = "create-perfect-world"
author = "ilGuappo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8242cb5fb5040dec215c31f092e4f68ab2eca2d118546d4bbec0923b1352499"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
